### ISSUE TITLE
Is this voice free for commercial use?

### ISSUE THREAD

**Issue by NeuroNoNeuro** [tts-fm/feedback#1]
I use MaryTTS for my voices for the express reason that it is free to use commercially or otherwise.  Is this voice free to use commercially?  Who's voice is it from?  Google?  I like the simplicity of this, and hope that it is free to use commercially, and that there will be more voices in the future.

**Comment by huan9huan** [comment]
glad to know someone like it.
it's free to be used commercially.
will be more voices, but not our focus, because not stable enough for now.
